---
- hosts: all
  tasks:
    - name: 'Install all dependencies'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - apache2
        - libapache2-mod-php5
        - php5-gd
        - libssh2-php
        - php5-mcrypt
        - php5-mysql
        - mysql-server-5.6
        - python-mysqldb

    - name: 'Create mysql database'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: 'Create a mysql user'
      myql_user:
        login_user: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present

    - name: 'Download the wordpress package'
      get_url:
        url: 'https://br.wordpress.org/wordpress-4.9.1-pt_BR.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Uncompress the wordpress file'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: true

    - name: 'Copy Wordpress wp-config.php'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: true

    - name: 'Configure the wp-config with the entries of database'     
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
      become: true
