---
- hosts: all
  tasks:
    - name: 'Install all dependencies'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - apache2
        - libapache2-mod-php5
        - php5-gd
        - libssh2-php
        - php5-mcrypt
        - php5-mysql
        - mysql-server-5.6
        - python-mysqldb